on: 
jobs:
  first_job :
     runs-on: ubuntu-latest
     steps :
        - name: print greeting
          run: echo " Hii , How are you? "
        - name: print reply 
          run : echo " I am fine "




